//? Shuffling and sampling
/*
 *   Shuffling sets values into a random, disordered sequence (opposite of sorting)
 *   Sampling selects a set of values randomly (opposite of selecting)
 *
 *   Sorting and selecting brings order and consistency, while shuffling and sampling bring disorder
 *   and randomness
 *
 *   The Math.random() is an algorithm that produces random numbers in such a way that the properties of
 *   the generated sequence are approximately that of a sequence of truly random numbers. But because this
 *   numbers are generated by an automated procedure means that they are not trully random, so they are
 *   called pseudorandom numbers
 *
 *   Using the random function we can generate useful functions for this chapter
 */

//* It behaves as a coin toss. We use this function when we want to decide between two alternatives randomly
const randomBit = () => Math.random() >= 0.5;
//* It returns a random floating number between a and b
const randomNum = (a, b) => a + (b - a) * Math.random();
//* Same as the previous but returning integer values
const randomInt = (a, b) => Math.floor(randomNum(a, b));
