//? Shuffling and sampling
/*
 *   Shuffling sets values into a random, disordered sequence (opposite of sorting)
 *   Sampling selects a set of values randomly (opposite of selecting)
 *
 *   Sorting and selecting brings order and consistency, while shuffling and sampling bring disorder
 *   and randomness
 *
 *   The Math.random() is an algorithm that produces random numbers in such a way that the properties of
 *   the generated sequence are approximately that of a sequence of truly random numbers. But because this
 *   numbers are generated by an automated procedure means that they are not trully random, so they are
 *   called pseudorandom numbers
 *
 *   Using the random function we can generate useful functions for this chapter
 */

//* It behaves as a coin toss. We use this function when we want to decide between two alternatives randomly
const randomBit = () => Math.random() >= 0.5;
//* It returns a random floating number between a and b
const randomNum = (a, b) => a + (b - a) * Math.random();
//* Same as the previous but returning integer values
const randomInt = (a, b) => Math.floor(randomNum(a, b));


//? Shuffling
/*
*   First we will shuffle an array of values in order to produce a random sequence of values, or using a
*   mathematical term, a permutation.
*   A real world example is shuffling a deck of cards before playing a game to start anew with a different
*   sequence of cards every time

*   An important requisite is that every possible permutation should be equally likely, and that is something
*   difficult to test

*   A way to do so would be to run the algorithm many times with a known input sequence and test statistically
*   whether the observed outcomes suggest a uniform distribution
*/

//? Shuffling by sorting
//* It does not have the best performance, but it's the simplest implementation
//* To shuffle a set of values:
//* 1. Associate a random number with each value
//* 2. Sort the set on that random value
//* The result will be a totally random shuflle